trigger:
- master

jobs:
- job: Build
  timeoutInMinutes: 240
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      choco sources add -n=roswin -s https://roswin.azurewebsites.net/api/v2/ --priority 1
      choco install hg
      choco install boost
      choco install pkg-config
      choco install freeimage
      choco install protobuf
      choco install qt5-sdk
      choco install dlfcn-win32
      choco install libcurl
      choco install ogre
      choco install zeromq
      choco install cppzmq
      choco install tbb
      choco install qwt
  - script: |
      set "PATH=C:\Program Files\Mercurial;%PATH%"
      hg clone https://bitbucket.org/ignitionrobotics/ign-cmake -r ign-cmake0
      hg clone https://bitbucket.org/ignitionrobotics/ign-math -r ign-math4
      hg clone https://bitbucket.org/seanyen-msft/sdformat -r sdf6
      hg clone https://bitbucket.org/ignitionrobotics/ign-msgs -r ign-msgs1
      hg clone https://bitbucket.org/ignitionrobotics/ign-tools -r default
      hg clone https://bitbucket.org/seanyen-msft/ign-transport -r ign-transport4
      hg clone https://bitbucket.org/seanyen-msft/gazebo -r gazebo9
  - script: |
      call "setup.bat"
      mkdir ign-cmake\build & cd ign-cmake\build
      cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=c:\opt\rosdeps\x64 -DCMAKE_INSTALL_PREFIX=c:\opt\rosdeps\x64 -G "Ninja" ..
      ninja install
  - script: |
      call "setup.bat"
      mkdir ign-math\build & cd ign-math\build
      cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=c:\opt\rosdeps\x64 -DCMAKE_INSTALL_PREFIX=c:\opt\rosdeps\x64 -G "Ninja" ..
      ninja install
  - script: |
      set PATH=C:\opt\rosdeps\x64\tools\protobuf;%PATH%
      call "setup.bat"
      mkdir ign-msgs\build & cd ign-msgs\build
      cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=c:\opt\rosdeps\x64 -DCMAKE_INSTALL_PREFIX=c:\opt\rosdeps\x64 -G "Ninja" ..
      ninja install
  - script: |
      call "setup.bat"
      mkdir ign-tools\build & cd ign-tools\build
      cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=c:\opt\rosdeps\x64 -DCMAKE_INSTALL_PREFIX=c:\opt\rosdeps\x64 -G "Ninja" ..
      ninja install
  - script: |
      call "setup.bat"
      mkdir ign-transport\build & cd ign-transport\build
      cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=c:\opt\rosdeps\x64 -DCMAKE_INSTALL_PREFIX=c:\opt\rosdeps\x64 -G "Ninja" ..
      ninja install
  - script: |
      call "setup.bat"
      mkdir sdformat\build & cd sdformat\build
      cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=c:\opt\rosdeps\x64 -DCMAKE_INSTALL_PREFIX=c:\opt\rosdeps\x64 -G "Ninja" ..
      ninja install
  - script: |
      set PATH=C:\opt\rosdeps\x64\tools\protobuf;%PATH%
      call "setup.bat"
      mkdir gazebo\build & cd gazebo\build
      cmake --debug-output -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=c:\opt\rosdeps\x64 -DCMAKE_INSTALL_PREFIX=c:\opt\rosdeps\x64 -G "Ninja" ..
      ninja install
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'c:\opt'
      artifactName: 'opt'
