trigger:
- master

jobs:
- job: Build
  timeoutInMinutes: 240
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      choco sources add -n=roswin -s https://roswin.azurewebsites.net/api/v2/ --priority 1
      choco install hg
      choco install boost
      choco install pkg-config
      choco install freeimage
      choco install protobuf
      choco install qt5-sdk
      choco install dlfcn-win32
      choco install libcurl
  - script: |
      set "PATH=C:\Program Files\Mercurial;%PATH%"
      hg clone https://bitbucket.org/ignitionrobotics/ign-cmake -r ign-cmake0
      hg clone https://bitbucket.org/ignitionrobotics/ign-math -r ign-math4
      hg clone https://bitbucket.org/osrf/sdformat -r sdf6
      hg clone https://bitbucket.org/ignitionrobotics/ign-msgs -r ign-msgs1
      hg clone https://bitbucket.org/osrf/gazebo -r gazebo9
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      mkdir ign-cmake\build & cd ign-cmake\build
      cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_PREFIX_PATH=c:\opt\rosdeps\x64 -DCMAKE_INSTALL_PREFIX=c:\opt\rosdeps\x64 -G "NMake Makefiles" ..
      nmake install
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      mkdir ign-math\build & cd ign-math\build
      cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_PREFIX_PATH=c:\opt\rosdeps\x64 -DCMAKE_INSTALL_PREFIX=c:\opt\rosdeps\x64 -G "NMake Makefiles" ..
      nmake install
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      mkdir sdformat\build & cd sdformat\build
      cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_PREFIX_PATH=c:\opt\rosdeps\x64 -DCMAKE_INSTALL_PREFIX=c:\opt\rosdeps\x64 -G "NMake Makefiles" ..
      nmake install
  - script: |
      set PATH=C:\opt\rosdeps\x64\tools\protobuf;%PATH%
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      mkdir ign-msgs\build & cd ign-msgs\build
      cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_PREFIX_PATH=c:\opt\rosdeps\x64 -DCMAKE_INSTALL_PREFIX=c:\opt\rosdeps\x64 -G "NMake Makefiles" ..
      nmake install
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      mkdir gazebo\build & cd gazebo\build
      cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_PREFIX_PATH=c:\opt\rosdeps\x64 -DCMAKE_INSTALL_PREFIX=c:\opt\rosdeps\x64 -G "NMake Makefiles" ..
      nmake install
