variables:
  GAZEBO_INSTALL_PREFIX: 'c:\opt\rosdeps\x64'

trigger:
- master

jobs:
- job: Build
  timeoutInMinutes: 240
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      choco sources add -n=roswin -s https://roswin.azurewebsites.net/api/v2/ --priority 1
      choco upgrade hg 7zip
      choco upgrade pkg-config boost freeimage protobuf qt5-sdk dlfcn-win32 libcurl ogre zeromq cppzmq tbb qwt
    displayName: Install system dependencies
  - script: |
      set "PATH=C:\Program Files\Mercurial;%PATH%"
      hg clone https://bitbucket.org/seanyen-msft/ign-cmake -r ign-cmake0_windows
      hg clone https://bitbucket.org/ignitionrobotics/ign-math -r ign-math4
      hg clone https://bitbucket.org/seanyen-msft/sdformat -r sdf6
      hg clone https://bitbucket.org/ignitionrobotics/ign-msgs -r ign-msgs1
      hg clone https://bitbucket.org/ignitionrobotics/ign-tools -r default
      hg clone https://bitbucket.org/seanyen-msft/ign-transport -r ign-transport4
      hg clone https://bitbucket.org/seanyen-msft/gazebo -r gazebo9
    displayName: Get sources
  - script: |
      call "build.bat" ign-cmake
    displayName: ign-cmake
  - script: |
      call "build.bat" ign-math
    displayName: ign-math
  - script: |
      set PATH=C:\opt\rosdeps\x64\tools\protobuf;%PATH%
      call "build.bat" ign-msgs
    displayName: ign-msgs
  - script: |
      call "build.bat" ign-tools
    displayName: ign-tools
  - script: |
      call "build.bat" ign-transport
    displayName: ign-transport
  - script: |
      call "build.bat" sdformat
    displayName: sdformat
  - script: |
      set PATH=C:\opt\rosdeps\x64\tools\protobuf;%PATH%
      call "build.bat" gazebo "--debug-output -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON -DCMAKE_VERBOSE_MAKEFILE=ON"
    displayName: gazebo
  - script: |
      powershell.exe -noexit -file "copy_binaries.ps1"
    displayName: Copy binaries
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'opt'
