variables:
  GAZEBO_INSTALL_PREFIX: 'c:\opt\rosdeps\x64'
  GAZEBO_CMAKE_BUILD_TYPE: 'RelWithDebInfo'
  GAZEBO_CMAKE_PDB_OUTPUT_DIRECTORY: '$(Build.ArtifactStagingDirectory)\symbols'

trigger:
- master

jobs:
- job: Build
  timeoutInMinutes: 240
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      choco sources add -n=roswin -s https://roswin.azurewebsites.net/api/v2/ --priority 1
      choco upgrade hg 7zip
      choco upgrade pkg-config boost freeimage protobuf qt5-sdk dlfcn-win32 libcurl ogre zeromq cppzmq tbb qwt
    displayName: Install system dependencies
  - script: |
      set "PATH=C:\Program Files\Mercurial;%PATH%"
      hg clone https://bitbucket.org/ignitionrobotics/ign-cmake -r ign-cmake0
      hg clone https://bitbucket.org/ignitionrobotics/ign-math -r ign-math4
      hg clone https://bitbucket.org/ignitionrobotics/ign-msgs -r ign-msgs1
      hg clone https://bitbucket.org/ignitionrobotics/ign-tools -r ign-tools0
      hg clone https://bitbucket.org/ignitionrobotics/ign-transport -r ign-transport4
      hg clone https://bitbucket.org/osrf/sdformat -r sdformat6_6.2.0
      hg clone https://bitbucket.org/osrf/gazebo -r gazebo9
    displayName: Get sources
  - script: |
      call "build.bat" ign-cmake "-DBUILD_TESTING:BOOL=False"
    displayName: ign-cmake
  - script: |
      call "build.bat" ign-math "-DBUILD_TESTING:BOOL=False"
    displayName: ign-math
  - script: |
      call "build.bat" ign-tools "-DBUILD_TESTING:BOOL=False"
    displayName: ign-tools
  - script: |
      set PATH=C:\opt\rosdeps\x64\tools\protobuf;%PATH%
      call "build.bat" ign-msgs "-DBUILD_TESTING:BOOL=False"
    displayName: ign-msgs
  - script: |
      call "build.bat" ign-transport "-DBUILD_TESTING:BOOL=False"
    displayName: ign-transport
  - script: |
      call "build.bat" sdformat "-DBUILD_TESTING:BOOL=False"
    displayName: sdformat
  - script: |
      set PATH=C:\opt\rosdeps\x64\tools\protobuf;%PATH%
      call "build.bat" gazebo "--debug-output -DCMAKE_VERBOSE_MAKEFILE=ON"
    displayName: gazebo
  - script: |
      powershell.exe -noexit -file "copy_binaries.ps1"
    displayName: Copy binaries
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'opt'
- job: OSRF_integration_staging
  timeoutInMinutes: 240
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      choco upgrade hg wget -y
  - script: |
      set "PATH=C:\Program Files\Mercurial;%PATH%"
      hg clone https://bitbucket.org/osrf/release-tools scripts -r default
      hg clone https://bitbucket.org/seanyen-msft/gazebo -r gazebo9_windows_staging
      set MAKE_JOBS=%NUMBER_OF_PROCESSORS%
      set WORKSPACE=%CD%
      call ".\scripts\jenkins-scripts\gazebo-default-devel-windows7-amd64.bat"
