variables:
  GAZEBO_INSTALL_PREFIX: 'c:\opt\rosdeps\x64'
  GAZEBO_CMAKE_BUILD_TYPE: 'RelWithDebInfo'
  GAZEBO_CMAKE_PDB_OUTPUT_DIRECTORY: '$(Build.ArtifactStagingDirectory)\symbols'

trigger:
- master

jobs:
- job: Build
  timeoutInMinutes: 240
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      choco sources add -n=roswin -s https://roswin.azurewebsites.net/api/v2/ --priority 1
      choco upgrade hg 7zip
      choco upgrade pkg-config boost freeimage protobuf qt5-sdk dlfcn-win32 libcurl ogre zeromq cppzmq tbb qwt
    displayName: Install system dependencies
  - script: |
      set "PATH=C:\Program Files\Mercurial;%PATH%"
      hg clone https://bitbucket.org/seanyen-msft/ign-cmake -r ignition-cmake_0.6.1_windows
      hg clone https://bitbucket.org/ignitionrobotics/ign-math -r ignition-math4_4.0.0
      hg clone https://bitbucket.org/ignitionrobotics/ign-msgs -r ignition-msgs_1.0.0
      hg clone https://bitbucket.org/ignitionrobotics/ign-tools -r ignition-tools_0.1.0
      hg clone https://bitbucket.org/ignitionrobotics/ign-transport -r ignition-transport4_4.0.0
      hg clone https://bitbucket.org/seanyen-msft/sdformat -r sdformat6_6.1.0_windows
      hg clone https://bitbucket.org/seanyen-msft/gazebo -r gazebo9_9.5.0_windows
    displayName: Get sources
  - script: |
      call "build.bat" ign-cmake "-DBUILD_TESTING:BOOL=False"
    displayName: ign-cmake
  - script: |
      call "build.bat" ign-math "-DBUILD_TESTING:BOOL=False"
    displayName: ign-math
  - script: |
      call "build.bat" ign-tools "-DBUILD_TESTING:BOOL=False"
    displayName: ign-tools
  - script: |
      set PATH=C:\opt\rosdeps\x64\tools\protobuf;%PATH%
      call "build.bat" ign-msgs "-DBUILD_TESTING:BOOL=False"
    displayName: ign-msgs
  - script: |
      call "build.bat" ign-transport "-DBUILD_TESTING:BOOL=False"
    displayName: ign-transport
  - script: |
      call "build.bat" sdformat "-DBUILD_TESTING:BOOL=False"
    displayName: sdformat
  - script: |
      set PATH=C:\opt\rosdeps\x64\tools\protobuf;%PATH%
      call "build.bat" gazebo "--debug-output -DCMAKE_VERBOSE_MAKEFILE=ON"
    displayName: gazebo
  - script: |
      powershell.exe -noexit -file "copy_binaries.ps1"
    displayName: Copy binaries
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'opt'
- job: OSRF
  timeoutInMinutes: 240
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      choco upgrade hg wget -y
  - script: |
      set "PATH=C:\Program Files\Mercurial;%PATH%"
      hg clone https://bitbucket.org/seanyen-msft/release-tools scripts -r default_staging
      hg clone https://bitbucket.org/seanyen-msft/gazebo -r gazebo9_9.5.0_staging
      set MAKE_JOBS=%NUMBER_OF_PROCESSORS%
      set WORKSPACE=%CD%
      call ".\scripts\jenkins-scripts\gazebo-default-devel-windows7-amd64.bat"
- job: OSRF_integration
  timeoutInMinutes: 240
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      choco upgrade hg wget -y
  - script: |
      set "PATH=C:\Program Files\Mercurial;%PATH%"
      hg clone https://bitbucket.org/osrf/release-tools scripts -r update_gazebo9_build
      hg clone https://bitbucket.org/osrf/gazebo -r gazebo9.5.0_seanyen-msft
      set MAKE_JOBS=%NUMBER_OF_PROCESSORS%
      set WORKSPACE=%CD%
      call ".\scripts\jenkins-scripts\gazebo-default-devel-windows7-amd64.bat"
